name: 🔧 Build (dry-run)

on:
  workflow_dispatch:
  push:
    branches:
      - develop
  pull_request_target:
    types:
      - opened
      - reopened
      - edited
      - synchronize
jobs:
  build-dry-run:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}
    env:
      PUBLIC_DEV_PORT: 3002
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref_name }}

      - name: Prepare Code
        uses: ./.github/actions/prepare-code

      - name: Build site
        run: npm run build
